name: Run Procursus

on:
  workflow_dispatch:
    inputs:
      rule:
        description: "Rule to pass to make (e.g nano-package)"
        required: false
      target:
        description: "Target to build for (e.g iphoneos-arm64)"
        required: false
        default: "iphoneos-arm64-rootless"
      cfver:
        description: "iOS version to build for (e.g 1800 for iOS 15)"
        required: false
        default: "2000"
      source:
        description: "Specific Procursus repository (e.g ProcursusTeam/Procursus)"
        required: false
        default: "johnnyp382/Procursus"
      branch:
        description: "Branch in source to checkout"
        required: false
        default: "main"
      upload-base:
        description: "Upload existant build_base"
        required: false
        default: "false"
      upload-dist:
        description: "Upload existant build_dist"
        required: false
        default: "true"
  
jobs:
  Bootstrap:
    runs-on: self-hosted
    name: Bootstrap MacOS
    steps: 
      - name: Procursus Boot
        uses: beerpiss/procursus-action@v2  # the v2 tag refers to the latest of major version 2 (currently 2.0)
        with:
          packages: apt autoconf automake autopoint bash bison build-essential ca-certificates clang-16 clang cmake-data cmake coreutils curl darwintools dash dirmngr docbook-xml docbook-xsl dpkg fakeroot file findutils flex gawk gettext-base gettext git gnupg-utils gnupg gpg-agent gpg-wks-client gpg-wks-server gpg gpgconf gpgsm gpgv grep groff gzip ld64 ldid less libapt-pkg6.0 libarchive13 libassuan0 libbrotli1 libc++-16-dev libc++-dev libc-ares2 libclang-common-16-dev libclang-cpp16 libcurl4 libedit0 libffi8 libfl-dev libfl2 libgcrypt20 libgdbm6 libglib2.0-0 libgmp10 libgnutls30 libgpg-error0 libhogweed6 libidn2-0 libintl8 libksba8 libllvm16 liblocale-gettext-perl liblz4-1 liblzma5 liblzo2-2 libmagic1 libmd0 libmpfr6 libncursesw6 libnettle8 libnghttp2-14 libnpth0 libp11-kit0 libpcre2-8-0 libplist3 libpod-parser-perl libpython3.9 libreadline8 librtmp1 libsgmls-perl libsqlite3-1 libssh2-1 libssl3 libtapi libtasn1-6 libterm-readkey-perl libtextstyle0v5 libtool libunistring5 libusb-1.0-0 libuuid16 libuv1 libxar1 libxml2-utils libxml2 libxxhash0 libyaml-tiny-perl libz-ng2 libzstd1 llvm-16-dev llvm-16-linker-tools llvm-16-runtime llvm-16 llvm-dev m4 make ncurses-bin ncurses-term odcctools openssl patch perl pinentry pkg-config po4a procursus-keyring python3.9 python3 scdaemon sed tar triehash uikittools xz-utils zstd
    
  procursus:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus
    steps:
      - name: Installs Procursus with GitHub action
        uses: beer-psi/procursus-action@v2.0.2

      
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  procursus-with-packages:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus with extra packages
    steps:
      - name: Installs Procursus with GitHub action
        uses: beer-psi/procursus-action@v2.0.2
        with:
          packages: cmake clang
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  
  run-procursus:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Run ${{ github.event.inputs.rule }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "${{ github.event.inputs.source }}"
          ref: "${{ github.event.inputs.branch }}"
          
      - name: Setup Procursus
        uses: beer-psi/procursus-action@v2.0.2
        with:
          packages: odcctools autoconf automake autopoint bash bison cmake curl docbook-xml docbook-xsl fakeroot findutils flex gawk git gnupg groff grep gzip ldid ld64 libtool make ncurses-bin openssl patch pkg-config po4a python3 sed tar triehash xz-utils zstd
          cache: true

      - name: Build
        run: |
          gmake ${{ github.event.inputs.rule }} \
            MEMO_TARGET=${{ github.event.inputs.target }} \
            MEMO_CFVER=${{ github.event.inputs.cfver }} \
            BUILD_ROOT="${{ github.workspace }}" NO_PGP=1

      - name: Check for build_{base,dist}
        id: info
        run: |
          if [ -d "build_base" ]; then
              echo "::set-output name=build-base-exists::true"
          else
              echo "::set-output name=build-base-exists::false"
          fi

          if [ -d "build_dist" ]; then
              echo "::set-output name=build-dist-exists::true"
          else
              echo "::set-output name=build-dist-exists::false"
          fi

      - name: Upload build_base
        if: steps.info.outputs.build-base-exists == 'true' && github.event.inputs.upload-base == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: build_base
          path: build_base/

      - name: Upload build_dist
        if: steps.info.outputs.build-dist-exists == 'true' && github.event.inputs.upload-dist == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: build_dist
          path: build_dist/

          
