run-procursus:
  runs-on: macos-14
  if: "!contains(github.event.head_commit.message, 'skip-ci')"
  name: Run ${{ github.event.inputs.rule }}
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: "${{ github.event.inputs.source }}"
        ref: "${{ github.event.inputs.branch }}"
        
    - name: Setup Procursus
      uses: beer-psi/procursus-action@v2.0.2
      with:
        packages: odcctools autoconf automake autopoint bash bison build-essential cmake curl docbook-xml docbook-xsl fakeroot findutils flex gawk git gnupg groff grep gtk-doc-tools gzip ldid l...
        cache: true

    - name: Build
      run: |
        arch -arm64 gmake ${{ github.event.inputs.rule }} \
          MEMO_TARGET=${{ github.event.inputs.target }} \
          MEMO_CFVER=${{ github.event.inputs.cfver }} \
          BUILD_ROOT="${{ github.workspace }}" NO_PGP=1
    - name: Check for build_{base,work,dist}
      id: info
      run: |
        if [ -d "build_base" ]; then
            echo "::set-output name=build-base-exists::true"
        else
            echo "::set-output name=build-base-exists::false"
        fi
        if [ -d "build_work" ]; then
            echo "::set-output name=build-work-exists::true"
        else
            echo "::set-output name=build-work-exists::false"
        fi          
        if [ -d "build_dist" ]; then
            echo "::set-output name=build-dist-exists::true"
        else
            echo "::set-output name=build-dist-exists::false"
        fi
    - name: Upload build_base
      if: steps.info.outputs.build-base-exists == 'true' && github.event.inputs.upload-base == 'true'
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build_base
        path: build_base/

    - name: Upload build_work
      if: steps.info.outputs.build-work-exists == 'true' && github.event.inputs.upload-work == 'true'
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build_work
        path: build_work/          

    - name: Upload build_dist
      if: steps.info.outputs.build-dist-exists == 'true' && github.event.inputs.upload-dist == 'true'
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build_dist
        path: build_dist/