name: Run Procursus

on:
  workflow_dispatch:
    inputs:
      rule:
        description: "Rule to pass to make (e.g nano-package)"
        required: true
      target:
        description: "Target to build for (e.g iphoneos-arm64)"
        required: false
        default: "iphoneos-arm64"
      cfver:
        description: "iOS version to build for (e.g 1800 for iOS 15)"
        required: false
        default: "1700"
      source:
        description: "Specific Procursus repository (e.g ProcursusTeam/Procursus)"
        required: false
        default: "ProcursusTeam/Procursus"
      branch:
        description: "Branch in source to checkout"
        required: false
        default: "main"
      upload-base:
        description: "Upload existant build_base"
        required: false
        default: "false"
      upload-dist:
        description: "Upload existant build_dist"
        required: false
        default: "true"
  
jobs:
  procursus:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus
    steps:
      - name: Installs Procursus with GitHub action
        uses: beer-psi/procursus-action@v2.0.2


      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  procursus-with-packages:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus with extra packages
    steps:
      - name: Installs Procursus with GitHub action
        uses: beer-psi/procursus-action@v2.0.2
        with:
          packages: cmake clang
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  procursus-no-cache:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus (no cache)
    steps:
      - name: Installs Procursus with GitHub action 
        uses: beer-psi/procursus-action@v2.0.2
        with:
         cache: false
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  procursus-installed-twice:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus (twice)
    steps:
      - name: Installs Procursus with GitHub action 
        uses: beer-psi/procursus-action@v2.0.2
      - name: Installs ldid and make with the same action
        uses: beer-psi/procursus-action@v2.0.2
        with:
          packages: ldid make
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt list
  procursus-custom-mirror:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    name: Installs Procursus with a different mirror
    steps:
      - name: Installs Procursus with GitHub action 
        uses: beer-psi/procursus-action@v2.0.2
        with:
          mirror: https://apt.procurs.us
          suites: big_sur
          components: main testing
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt list

